# Pandas

In [3]:
import pandas as pd
a = [1,2,3,4,5]
var = pd.Series(a)
print(var)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
#Agar index ko khud badalna ho to
var = pd.Series(a,index=["a","b","c","d","e"])
print(var)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [6]:
#agar dictionary ko use karna ho to asay kary gay
dic = {
    "Name":["python","c++","r","c"],
    "Learn":[80,60,0,50],
    "rank":[90,82,88,78]
}
var1 =pd.Series(dic)
var1

Name     [python, c++, r, c]
Learn        [80, 60, 0, 50]
rank        [90, 82, 88, 78]
dtype: object

# DataFrame

In [7]:
import pandas as pd

In [9]:
b = [5,6,7,8,9,10]
var2 = pd.DataFrame(b)
var2

    0
0   5
1   6
2   7
3   8
4   9
5  10

In [14]:
#DataFrame dictionary ma kasa hota hai
dic2 ={
    "Name":["Majid","Hammad","Awais","Danial","Abu_Huraira"],
    "Roll_Number":[64,33,53,62,46],
    "Rank":[77,99,23,43,22]
}
var3=pd.DataFrame(dic2)
var3

          Name  Roll_Number  Rank
0        Majid           64    77
1       Hammad           33    99
2        Awais           53    23
3       Danial           62    43
4  Abu_Huraira           46    22

In [15]:
#ab mujy agar name ma say Danial ko lana ho to
print(var3["Name"][3])

Danial

In [19]:
#agar mujy abu_huraira ka rank chahiya
print(var3["Rank"][4])

22

# 2D Array

In [17]:
list_1 = [[1,2,3],[4,5,6]]
var4 = pd.DataFrame(list_1)
var4

   0  1  2
0  1  2  3
1  4  5  6

In [20]:
#agar dictionary2 ma sy koi specific column ko select karna ho to kasy karty hai
print(var3["Name"])

0          Majid
1         Hammad
2          Awais
3         Danial
4    Abu_Huraira
Name: Name, dtype: object

In [31]:
dic5 ={
    "Friend":["Abu_Huraira","Danial","Abu_Bakar","Ahmad","Fazal"],
    "Roll_Number":[78,45,96,57,68],
    "CGPA":[2.85,2.23,2.24,2.84,2.72],
    "Value":["High","No","No","Good","Moderate"],
    "Personality":["Excelent","Good","Normal","Nice","Good"]
}
var5 =pd.DataFrame(dic5)
var5

        Friend  Roll_Number  CGPA     Value Personality
0  Abu_Huraira           78  2.85      High    Excelent
1       Danial           45  2.23        No        Good
2    Abu_Bakar           96  2.24        No      Normal
3        Ahmad           57  2.84      Good        Nice
4        Fazal           68  2.72  Moderate        Good

# Insert and Delete

In [32]:
#ab agar mujy Friend k bad or Roll_Number sy pehly koi nya column ko add karna ho to inset use hota hai 
var5.insert(1,"Place",["Abdullah_pur","City","City","Kot_Nanak","Kot_Hassan"])
var5

        Friend         Place  Roll_Number  CGPA     Value Personality
0  Abu_Huraira  Abdullah_pur           78  2.85      High    Excelent
1       Danial          City           45  2.23        No        Good
2    Abu_Bakar          City           96  2.24        No      Normal
3        Ahmad     Kot_Nanak           57  2.84      Good        Nice
4        Fazal    Kot_Hassan           68  2.72  Moderate        Good

In [33]:
del var5["Value"]
var5

        Friend         Place  Roll_Number  CGPA Personality
0  Abu_Huraira  Abdullah_pur           78  2.85    Excelent
1       Danial          City           45  2.23        Good
2    Abu_Bakar          City           96  2.24      Normal
3        Ahmad     Kot_Nanak           57  2.84        Nice
4        Fazal    Kot_Hassan           68  2.72        Good

In [34]:
var5

        Friend         Place  Roll_Number  CGPA Personality
0  Abu_Huraira  Abdullah_pur           78  2.85    Excelent
1       Danial          City           45  2.23        Good
2    Abu_Bakar          City           96  2.24      Normal
3        Ahmad     Kot_Nanak           57  2.84        Nice
4        Fazal    Kot_Hassan           68  2.72        Good

In [36]:
var5.to_csv("Majid_Friend.csv")

In [37]:
var5

        Friend         Place  Roll_Number  CGPA Personality
0  Abu_Huraira  Abdullah_pur           78  2.85    Excelent
1       Danial          City           45  2.23        Good
2    Abu_Bakar          City           96  2.24      Normal
3        Ahmad     Kot_Nanak           57  2.84        Nice
4        Fazal    Kot_Hassan           68  2.72        Good

In [38]:
var5.insert(2,"FriendShip",["100%","25%","100%","80%","85%"])
var5

        Friend         Place FriendShip  Roll_Number  CGPA Personality
0  Abu_Huraira  Abdullah_pur       100%           78  2.85    Excelent
1       Danial          City        25%           45  2.23        Good
2    Abu_Bakar          City       100%           96  2.24      Normal
3        Ahmad     Kot_Nanak        80%           57  2.84        Nice
4        Fazal    Kot_Hassan        85%           68  2.72        Good

# File Ko Read Karna

In [39]:
var5

        Friend         Place FriendShip  Roll_Number  CGPA Personality
0  Abu_Huraira  Abdullah_pur       100%           78  2.85    Excelent
1       Danial          City        25%           45  2.23        Good
2    Abu_Bakar          City       100%           96  2.24      Normal
3        Ahmad     Kot_Nanak        80%           57  2.84        Nice
4        Fazal    Kot_Hassan        85%           68  2.72        Good

In [41]:
df = pd.read_csv("Majid_Ali_Friends.csv")
df

,Student_ID,Name,Age,City,Department,CGPA,Attendance,Fee_Status,Gender,Marks
0,101,Ali,20.0,Lahore,CS,3.25,88.0,Paid,Male,78.0
1,102,Ahmed,21.0,Karachi,IT,2.85,76.0,Pending,Male,65.0
2,103,Sara,NaN,Islamabad,CS,NaN,91.0,Paid,Female,89.0
3,104,Usman,19.0,Lahore,NaN,3.60,NaN,Paid,Male,92.0
4,105,Ayesha,22.0,NaN,SE,2.95,82.0,NaN,Female,NaN
5,106,Hamza,20.0,Multan,CS,3.10,95.0,Pending,Male,81.0
6,107,Hina,NaN,Lahore,IT,2.70,68.0,Paid,NaN,55.0
7,108,Bilal,23.0,Karachi,CS,NaN,79.0,Paid,Male,73.0
8,109,Fatima,21.0,Islamabad,SE,3.45,NaN,Pending,Female,95.0
9,110,Zain,20.0,NaN,CS,2.80,85.0,Paid,Male,NaN
10,103,Sara,NaN,Islamabad,CS,NaN,91.0,Paid,Female,89.0
11,112,Maryam,22.0,Lahore,IT,3.05,73.0,NaN,Female,70.0

In [47]:
#agar mujy is ma sy kisi row ko lana ho to kia kary gay
df  =pd.read_csv("Majid_Ali_Friends.csv",usecols=["Department"])
df

   Department
0          CS
1          IT
2          CS
3         NaN
4          SE
5          CS
6          IT
7          CS
8          SE
9          CS
10         CS
11         IT

In [55]:
#agar mujjy specific row ko nikalna ho to 
df.loc[df["Name"]=="Maryam"]

Empty DataFrame
Columns: [Student_ID, Name, Age, City, Department, CGPA, Attendance, Fee_Status, Gender, Marks]
Index: []

In [57]:
df.loc[df["Student_ID"] == 110]

Empty DataFrame
Columns: [Student_ID, Name, Age, City, Department, CGPA, Attendance, Fee_Status, Gender, Marks]
Index: []

In [58]:
df["Student_ID"].dtype

dtype('int64')

In [60]:
df = pd.read_csv("Majid_Ali_Friends.csv")
df

,Student_ID,Name,Age,City,Department,CGPA,Attendance,Fee_Status,Gender,Marks
0,101,Ali,20.0,Lahore,CS,3.25,88.0,Paid,Male,78.0
1,102,Ahmed,21.0,Karachi,IT,2.85,76.0,Pending,Male,65.0
2,103,Sara,NaN,Islamabad,CS,NaN,91.0,Paid,Female,89.0
3,104,Usman,19.0,Lahore,NaN,3.60,NaN,Paid,Male,92.0
4,105,Ayesha,22.0,NaN,SE,2.95,82.0,NaN,Female,NaN
5,106,Hamza,20.0,Multan,CS,3.10,95.0,Pending,Male,81.0
6,107,Hina,NaN,Lahore,IT,2.70,68.0,Paid,NaN,55.0
7,108,Bilal,23.0,Karachi,CS,NaN,79.0,Paid,Male,73.0
8,109,Fatima,21.0,Islamabad,SE,3.45,NaN,Pending,Female,95.0
9,110,Zain,20.0,NaN,CS,2.80,85.0,Paid,Male,NaN
10,103,Sara,NaN,Islamabad,CS,NaN,91.0,Paid,Female,89.0
11,112,Maryam,22.0,Lahore,IT,3.05,73.0,NaN,Female,70.0

In [61]:
#agar mjy kisi specific row ko select karna ho to
df.loc[df["Student_ID"] == 112]

,Student_ID,Name,Age,City,Department,CGPA,Attendance,Fee_Status,Gender,Marks
11,112,Maryam,22.0,Lahore,IT,3.05,73.0,NaN,Female,70.0

In [62]:
df.loc[df["Name"]=="Sara"]

,Student_ID,Name,Age,City,Department,CGPA,Attendance,Fee_Status,Gender,Marks
2,103,Sara,NaN,Islamabad,CS,NaN,91.0,Paid,Female,89.0
10,103,Sara,NaN,Islamabad,CS,NaN,91.0,Paid,Female,89.0

In [63]:
df.head(5)

,Student_ID,Name,Age,City,Department,CGPA,Attendance,Fee_Status,Gender,Marks
0,101,Ali,20.0,Lahore,CS,3.25,88.0,Paid,Male,78.0
1,102,Ahmed,21.0,Karachi,IT,2.85,76.0,Pending,Male,65.0
2,103,Sara,NaN,Islamabad,CS,NaN,91.0,Paid,Female,89.0
3,104,Usman,19.0,Lahore,NaN,3.60,NaN,Paid,Male,92.0
4,105,Ayesha,22.0,NaN,SE,2.95,82.0,NaN,Female,NaN

In [64]:
df.tail(1)

,Student_ID,Name,Age,City,Department,CGPA,Attendance,Fee_Status,Gender,Marks
11,112,Maryam,22.0,Lahore,IT,3.05,73.0,NaN,Female,70.0

In [67]:
#dataset ma total kitna rows our columns hain yeh janine ke liya .shepe() ka use katy hai
df.shape

(12, 10)

In [68]:
#dataset ma data structure our missing values check karna 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  12 non-null     int64
 1   Name        12 non-null     object
 2   Age         9 non-null      float64
 3   City        10 non-null     object
 4   Department  11 non-null     object
 5   CGPA        9 non-null      float64
 6   Attendance  10 non-null     float64
 7   Fee_Status  10 non-null     object
 8   Gender      11 non-null     object
 9   Marks       10 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 1.1+ KB

In [69]:
#numeric values (salary,experience,rating ) ke mean,min,max,standard derivation sab ko eik sath dakhna ho
df.describe()

       Student_ID        Age      CGPA  Attendance      Marks
count   12.000000   9.000000  9.000000   10.000000  10.000000
mean   105.833333  20.888889  3.083333   82.800000  78.700000
std      3.433348   1.269296  0.302076    8.766096  12.987601
min    101.000000  19.000000  2.700000   68.000000  55.000000
25%    103.000000  20.000000  2.850000   76.750000  70.750000
50%    105.500000  21.000000  3.050000   83.500000  79.500000
75%    108.250000  22.000000  3.250000   90.250000  89.000000
max    112.000000  23.000000  3.600000   95.000000  95.000000

In [74]:
#condition lagani ho jsay jin ka cgpa 3 say uper ho wo kon hai
df[df["CGPA"]>3.0]

,Student_ID,Name,Age,City,Department,CGPA,Attendance,Fee_Status,Gender,Marks
0,101,Ali,20.0,Lahore,CS,3.25,88.0,Paid,Male,78.0
3,104,Usman,19.0,Lahore,NaN,3.60,NaN,Paid,Male,92.0
5,106,Hamza,20.0,Multan,CS,3.10,95.0,Pending,Male,81.0
8,109,Fatima,21.0,Islamabad,SE,3.45,NaN,Pending,Female,95.0
11,112,Maryam,22.0,Lahore,IT,3.05,73.0,NaN,Female,70.0

In [75]:
df[df["Age"]>22]

,Student_ID,Name,Age,City,Department,CGPA,Attendance,Fee_Status,Gender,Marks
7,108,Bilal,23.0,Karachi,CS,NaN,79.0,Paid,Male,73.0

In [76]:
#Misssing values ko check karna 
df.isna().sum()

Student_ID    0
Name          0
Age           3
City          2
Department    1
CGPA          3
Attendance    2
Fee_Status    2
Gender        1
Marks         2
dtype: int64