# Difference between CSV and XLS(excel) file format in Python Pandas

In [1]:
#andas mein kisi bhi data ko CSV file mein save karne ke liye hum to_csv() function ka istemal karte hain.
#Poora process sirf 3 steps ka hota hai:
#1. Python Dictionary banayein (Data tayar karein).
#2. Dictionary ko Pandas DataFrame (Table) mein convert karein.
#3. DataFrame ko to_csv() ke zariye file mein save kar deinm

In [6]:
import pandas as pd
friends =pd.DataFrame({
    "Name":["Majid","Abu_Huraira","Abu_Bakar","Rana Ahmad","Fazal Bhatti"],
    "Age":[22,21,20,22,21],
    "Resident":["City","Village","City","Village","Village"],
    "Cgpa":[3.09,2.85,2.24,2.84,2.72]
})
friends
friends.to_csv("My_Friends.csv")
friends

           Name  Age Resident  Cgpa
0         Majid   22     City  3.09
1   Abu_Huraira   21  Village  2.85
2     Abu_Bakar   20     City  2.24
3    Rana Ahmad   22  Village  2.84
4  Fazal Bhatti   21  Village  2.72

In [7]:
friends.to_csv("My_Friends.csv",index=False)
friends

           Name  Age Resident  Cgpa
0         Majid   22     City  3.09
1   Abu_Huraira   21  Village  2.85
2     Abu_Bakar   20     City  2.24
3    Rana Ahmad   22  Village  2.84
4  Fazal Bhatti   21  Village  2.72

# Read CSV files

In [8]:
df = pd.read_csv("My_Friends.csv")
df

           Name  Age Resident  Cgpa
0         Majid   22     City  3.09
1   Abu_Huraira   21  Village  2.85
2     Abu_Bakar   20     City  2.24
3    Rana Ahmad   22  Village  2.84
4  Fazal Bhatti   21  Village  2.72

# Basic CSV operation

In [10]:
#Top Rows Dekhna:df.head(2) =Sirf pehli 2 rows dikhayega.
df.head(2)

          Name  Age Resident  Cgpa
0        Majid   22     City  3.09
1  Abu_Huraira   21  Village  2.85

In [11]:
# Summary Info Dekhna:df.info()= Total rows, columns, aur data types batayega.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5 non-null      object
 1   Age       5 non-null      int64
 2   Resident  5 non-null      object
 3   Cgpa      5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [19]:
# agar kisi specific column ko select karna hot to
x = df[["Name","Age"]]
x

           Name  Age
0         Majid   22
1   Abu_Huraira   21
2     Abu_Bakar   20
3    Rana Ahmad   22
4  Fazal Bhatti   21

In [25]:
y = df["Cgpa"]
print(y)

0    3.09
1    2.85
2    2.24
3    2.84
4    2.72
Name: Cgpa, dtype: float64

In [26]:
df

           Name  Age Resident  Cgpa
0         Majid   22     City  3.09
1   Abu_Huraira   21  Village  2.85
2     Abu_Bakar   20     City  2.24
3    Rana Ahmad   22  Village  2.84
4  Fazal Bhatti   21  Village  2.72

In [30]:
a = pd.read_csv("My_Friends.csv",skiprows=[1])
print(a)

           Name  Age Resident  Cgpa
0   Abu_Huraira   21  Village  2.85
1     Abu_Bakar   20     City  2.24
2    Rana Ahmad   22  Village  2.84
3  Fazal Bhatti   21  Village  2.72

# Functions in Pandas of Python

In [3]:
import pandas as pd 
A = pd.read_csv("employees_practice.csv")
A

,Employee_ID,Name,Department,City,Salary,Experience_Yrs,Rating
0,101,Majid Ali,Data Science,Lahore,85000.0,3,4.5
1,102,Rana Ahmad,Web Dev,Islamabad,62000.0,1,3.8
2,103,Abu Bakar,Data Science,Lahore,95000.0,5,4.9
3,104,Abu Huraira,Cyber Security,Karachi,71000.0,2,4.1
4,105,Fazal Bhatti,Web Dev,Faisalabad,58000.0,1,3.5
5,106,Usman Khan,Data Science,Lahore,88000.0,4,4.6
6,107,Ali Raza,Cyber Security,Islamabad,NaN,3,3.9
7,108,Hamza Malik,Data Science,Karachi,91000.0,5,4.8
8,109,Saim Butt,Web Dev,Lahore,60000.0,2,NaN
9,110,Zain Hashmi,Cyber Security,Faisalabad,75000.0,3,4.2

In [2]:
#data kitna badha hai (shape) check karny  k lia
import pandas as pd
A.head(4)

NameError: name 'A' is not defined

In [4]:
X =pd.read_csv("employees_practice.csv")
X

,Employee_ID,Name,Department,City,Salary,Experience_Yrs,Rating
0,101,Majid Ali,Data Science,Lahore,85000.0,3,4.5
1,102,Rana Ahmad,Web Dev,Islamabad,62000.0,1,3.8
2,103,Abu Bakar,Data Science,Lahore,95000.0,5,4.9
3,104,Abu Huraira,Cyber Security,Karachi,71000.0,2,4.1
4,105,Fazal Bhatti,Web Dev,Faisalabad,58000.0,1,3.5
5,106,Usman Khan,Data Science,Lahore,88000.0,4,4.6
6,107,Ali Raza,Cyber Security,Islamabad,NaN,3,3.9
7,108,Hamza Malik,Data Science,Karachi,91000.0,5,4.8
8,109,Saim Butt,Web Dev,Lahore,60000.0,2,NaN
9,110,Zain Hashmi,Cyber Security,Faisalabad,75000.0,3,4.2

In [5]:
X.head(3) #agar mujy check karna ho k pehli row 3 kon c hai to head() fnction use kary ga

,Employee_ID,Name,Department,City,Salary,Experience_Yrs,Rating
0,101,Majid Ali,Data Science,Lahore,85000.0,3,4.5
1,102,Rana Ahmad,Web Dev,Islamabad,62000.0,1,3.8
2,103,Abu Bakar,Data Science,Lahore,95000.0,5,4.9

In [6]:
# agar mujy check karna ho k end par kon c rows hai to tail() function use kary gay
X.tail(5)

,Employee_ID,Name,Department,City,Salary,Experience_Yrs,Rating
5,106,Usman Khan,Data Science,Lahore,88000.0,4,4.6
6,107,Ali Raza,Cyber Security,Islamabad,NaN,3,3.9
7,108,Hamza Malik,Data Science,Karachi,91000.0,5,4.8
8,109,Saim Butt,Web Dev,Lahore,60000.0,2,NaN
9,110,Zain Hashmi,Cyber Security,Faisalabad,75000.0,3,4.2

In [9]:
# dataset ma check karna ho k total kitni rows our columns nhain yeh dakhny k liya X.shape use karty hai
X.shape

(10, 7)

In [10]:
# Data structure or missing value ko check karna
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Employee_ID     10 non-null     int64
 1   Name            10 non-null     object
 2   Department      10 non-null     object
 3   City            10 non-null     object
 4   Salary          9 non-null      float64
 5   Experience_Yrs  10 non-null     int64
 6   Rating          9 non-null      float64
dtypes: float64(2), int64(2), object(3)
memory usage: 692.0+ bytes

In [11]:
#Numeric values ka mean, median ,mode nikalna ho ta describe use karty hai
X.describe()

       Employee_ID        Salary  Experience_Yrs    Rating
count     10.00000      9.000000       10.000000  9.000000
mean     105.50000  76111.111111        2.900000  4.255556
std        3.02765  14198.982749        1.449138  0.477261
min      101.00000  58000.000000        1.000000  3.500000
25%      103.25000  62000.000000        2.000000  3.900000
50%      105.50000  75000.000000        3.000000  4.200000
75%      107.75000  88000.000000        3.750000  4.600000
max      110.00000  95000.000000        5.000000  4.900000

In [14]:
#Data condition ko check karna jasy k jin ki value 70,000 ho un ko print karo
high_salary =X[X["Salary"]>70000]
high_salary

,Employee_ID,Name,Department,City,Salary,Experience_Yrs,Rating
0,101,Majid Ali,Data Science,Lahore,85000.0,3,4.5
2,103,Abu Bakar,Data Science,Lahore,95000.0,5,4.9
3,104,Abu Huraira,Cyber Security,Karachi,71000.0,2,4.1
5,106,Usman Khan,Data Science,Lahore,88000.0,4,4.6
7,108,Hamza Malik,Data Science,Karachi,91000.0,5,4.8
9,110,Zain Hashmi,Cyber Security,Faisalabad,75000.0,3,4.2

In [15]:
# Missing value ko check karna or un ko bharna 
#pely check karna missing vales ko
X.isna().sum()

Employee_ID       0
Name              0
Department        0
City              0
Salary            1
Experience_Yrs    0
Rating            1
dtype: int64

In [20]:
#missing values ko bharna 
#missiong values ko avarage salary say fill karna
avg_salary = X["Salary"].mean()
X["Salary"] =X["Salary"].fillna(avg_salary)
print(avg_salary)

76111.11111111111

In [24]:
# Catagories ko count karna
X.count()

Employee_ID       10
Name              10
Department        10
City              10
Salary            10
Experience_Yrs    10
Rating             9
dtype: int64

In [27]:
# Data grouping k lia 
# department wise average salary nikalne k liya
X.groupby("Department")["Salary"].mean()

Department
Cyber Security    74037.037037
Data Science      89750.000000
Web Dev           60000.000000
Name: Salary, dtype: float64

In [28]:
# Data Sorting
# data ko salary k hisab say highest_t0_Lowest arrange karna
X.sort_values(by="Salary",ascending=False)

,Employee_ID,Name,Department,City,Salary,Experience_Yrs,Rating
2,103,Abu Bakar,Data Science,Lahore,95000.000000,5,4.9
7,108,Hamza Malik,Data Science,Karachi,91000.000000,5,4.8
5,106,Usman Khan,Data Science,Lahore,88000.000000,4,4.6
0,101,Majid Ali,Data Science,Lahore,85000.000000,3,4.5
6,107,Ali Raza,Cyber Security,Islamabad,76111.111111,3,3.9
9,110,Zain Hashmi,Cyber Security,Faisalabad,75000.000000,3,4.2
3,104,Abu Huraira,Cyber Security,Karachi,71000.000000,2,4.1
1,102,Rana Ahmad,Web Dev,Islamabad,62000.000000,1,3.8
8,109,Saim Butt,Web Dev,Lahore,60000.000000,2,NaN
4,105,Fazal Bhatti,Web Dev,Faisalabad,58000.000000,1,3.5